import jsPDF from 'jspdf';

const BRAND_COLOR = [47, 111, 237];
const TEXT_MUTED = [107, 107, 107];
const SUCCESS_COLOR = [30, 158, 90];
const DANGER_COLOR = [214, 69, 69];

function addHeader(doc, title, subjectCode) {
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, 210, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont(undefined, 'bold');
  doc.text('Quizora', 14, 15);

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.text(title, 14, 22);

  if (subjectCode) {
    doc.setFontSize(10);
    doc.setFont(undefined, 'bold');
    doc.text(subjectCode, 196, 15, { align: 'right' });
  }

  doc.setTextColor(0, 0, 0);
}

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text(
      `Generated by Quizora on ${new Date().toLocaleString('en-US')}`,
      14,
      287
    );
    doc.text(`Page ${i} of ${pageCount}`, 196, 287, { align: 'right' });

    doc.setFontSize(7.5);
    doc.setFont(undefined, 'italic');
    doc.setTextColor(160, 160, 160);
    doc.text('Powered by The Excel Foundation (TEF)', 105, 293, { align: 'center' });
  }
}

export function generateResultSummaryPDF(result, student) {
  const doc = new jsPDF();
  addHeader(doc, 'Exam Result Summary', result.subjectCode);

  let y = 42;
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(result.subjectName, 14, y);

  y += 10;
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(...TEXT_MUTED);
  doc.text('Student Name', 14, y);
  doc.text('Email', 90, y);
  doc.text('Submitted', 150, y);

  y += 6;
  doc.setTextColor(0, 0, 0);
  doc.setFont(undefined, 'bold');
  doc.text(student.fullName, 14, y);
  doc.setFont(undefined, 'normal');
  doc.setFontSize(9);
  doc.text(student.email || '—', 90, y);

  const submittedDate = result.submittedAt?.toDate
    ? result.submittedAt.toDate().toLocaleString('en-US')
    : '—';
  doc.text(submittedDate, 150, y);

  y += 14;
  doc.setDrawColor(220, 220, 220);
  doc.line(14, y, 196, y);
  y += 12;

  if (result.resultVisible) {
    const percentage = Math.round((result.score / result.totalQuestions) * 100);

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(...TEXT_MUTED);
    doc.text('Score', 14, y);
    doc.text('Correct', 75, y);
    doc.text('Incorrect', 120, y);
    doc.text('Time Used', 165, y);

    y += 8;
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(...BRAND_COLOR);
    doc.text(`${percentage}%`, 14, y);

    doc.setTextColor(...SUCCESS_COLOR);
    doc.text(String(result.score), 75, y);

    doc.setTextColor(...DANGER_COLOR);
    doc.text(String(result.totalQuestions - result.score), 120, y);

    doc.setTextColor(0, 0, 0);
    const minutes = Math.floor(result.timeTakenSeconds / 60);
    const seconds = result.timeTakenSeconds % 60;
    doc.text(`${minutes}m ${seconds}s`, 165, y);
  } else {
    doc.setFontSize(11);
    doc.setTextColor(...TEXT_MUTED);
    doc.text('Result is currently locked and pending release by the administrator.', 14, y);
  }

  addFooter(doc);
  doc.save(`Quizora-Result-${result.subjectCode || result.subjectName.replace(/\s+/g, '-')}.pdf`);
}

export function generateFullReviewPDF(result, student) {
  const doc = new jsPDF();
  addHeader(doc, 'Full Exam Review', result.subjectCode);

  let y = 42;
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(result.subjectName, 14, y);

  y += 8;
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(...TEXT_MUTED);
  doc.text(`${student.fullName} · ${student.email || ''}`, 14, y);
  y += 5;
  doc.text(`Score: ${result.score}/${result.totalQuestions}`, 14, y);

  y += 12;

  const LETTERS = ['A', 'B', 'C', 'D'];
  const pageWidth = 182;

  result.answers.forEach((ans, idx) => {
    const questionLines = doc.splitTextToSize(`Q${idx + 1}. ${ans.questionText}`, pageWidth);
    const estimatedHeight = questionLines.length * 5 + ans.options.length * 6 + 20;

    if (y + estimatedHeight > 275) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(10);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(questionLines, 14, y);
    y += questionLines.length * 5 + 2;

    doc.setFont(undefined, 'normal');
    ans.options.forEach((opt, optIdx) => {
      const isCorrect = optIdx === ans.correctIndex;
      const isSelected = optIdx === ans.selectedIndex;
      const isWrongSelected = isSelected && !isCorrect;

      if (isCorrect) {
        doc.setTextColor(...SUCCESS_COLOR);
      } else if (isWrongSelected) {
        doc.setTextColor(...DANGER_COLOR);
      } else {
        doc.setTextColor(60, 60, 60);
      }

      let label = `${LETTERS[optIdx]}. ${opt}`;
      if (isCorrect) label += '  (Correct Answer)';
      if (isWrongSelected) label += '  (Student\u2019s Answer)';

      const optLines = doc.splitTextToSize(label, pageWidth - 4);
      doc.text(optLines, 18, y);
      y += optLines.length * 5;
    });

    if (ans.explanation) {
      y += 2;
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont(undefined, 'italic');
      const explLines = doc.splitTextToSize(`Explanation: ${ans.explanation}`, pageWidth - 4);
      doc.text(explLines, 18, y);
      y += explLines.length * 5;
    }

    y += 8;
    doc.setDrawColor(230, 230, 230);
    doc.line(14, y - 4, 196, y - 4);
  });

  addFooter(doc);
  doc.save(`Quizora-Review-${result.subjectCode || result.subjectName.replace(/\s+/g, '-')}.pdf`);
}